/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonesystem.edu.view;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import phonesystem.edu.dao.TaiKhoanDAO;
import phonesystem.edu.ultil.MsgBox;

/**
 *
 * @author HienTran
 */
public class doiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form ResetPassword_Frame
     */
    public doiMatKhau() {
        initComponents();
        this.init();
    }

    private void init() {
        txtPassword.setBackground(new Color(0, 0, 0, 1));
        txtConfirm.setBackground(new Color(0, 0, 0, 1));

//        Password
        lblSlash.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblEye = new javax.swing.JLabel();
        lblSlash = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSpantext = new javax.swing.JLabel();
        lblSpantext1 = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        lbl_DatLaiMatKhau = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/ResetPassword_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/icons8_blind_23px.png"))); // NOI18N
        lblEye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEyeMouseClicked(evt);
            }
        });
        jPanel2.add(lblEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 130, 30, -1));

        lblSlash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/icons8_eye_23px.png"))); // NOI18N
        lblSlash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSlash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSlashMouseClicked(evt);
            }
        });
        jPanel2.add(lblSlash, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 130, 30, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/icons8_forgot_password_23px_1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 167, 22, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("<html>Đặt lại mật khẩu</html>");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 141, -1));

        lblSpantext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSpantext.setForeground(new java.awt.Color(131, 131, 131));
        lblSpantext.setText("Nhập lại mật khẩu mới");
        jPanel2.add(lblSpantext, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 168, 140, 23));

        lblSpantext1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSpantext1.setForeground(new java.awt.Color(131, 131, 131));
        lblSpantext1.setText("Mật khẩu mới");
        jPanel2.add(lblSpantext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 90, 23));

        txtConfirm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(131, 131, 131)));
        txtConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmFocusLost(evt);
            }
        });
        jPanel2.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 167, 232, 25));

        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(131, 131, 131)));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 130, 232, 25));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/icons8_forgot_password_23px_1.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 130, 22, -1));

        lbl_DatLaiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/ForgotPassbutton.png"))); // NOI18N
        lbl_DatLaiMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_DatLaiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_DatLaiMatKhauMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_DatLaiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 241, -1, 33));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 302, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEyeMouseClicked
        lblSlash.setVisible(true);
        lblEye.setVisible(false);
        txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lblEyeMouseClicked

    private void lblSlashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSlashMouseClicked
        lblSlash.setVisible(false);
        lblEye.setVisible(true);
        txtPassword.setEchoChar('.');
    }//GEN-LAST:event_lblSlashMouseClicked

    private void txtConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusGained
        lblSpantext.setVisible(false);
    }//GEN-LAST:event_txtConfirmFocusGained

    private void txtConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusLost
        if (txtConfirm.getPassword().length == 0) {
            lblSpantext.setVisible(true);
        } else {
            lblSpantext.setVisible(false);
        }
    }//GEN-LAST:event_txtConfirmFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        lblSpantext1.setVisible(false);
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if (txtPassword.getPassword().length == 0) {
            lblSpantext1.setVisible(true);
        } else {
            lblSpantext1.setVisible(false);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void lbl_DatLaiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_DatLaiMatKhauMouseClicked
        TaiKhoanDAO tkDAO = new TaiKhoanDAO();

        if (txtPassword.getText().equals("")) {
            MsgBox.alert(this, "Bạn chưa nhập Password!!!");
            return;
        } else if (txtConfirm.getText().equals("")) {
            MsgBox.alert(this, "Bạn chưa nhập Confirm!!!");
            return;
        } else if (!txtConfirm.getText().equals(txtPassword.getText())) {
            MsgBox.alert(this, "Confirm không trùng với Password!!!");
            return;
        } else {
            try {
                tkDAO.updateByEmail(txtPassword.getText(), nhapEmail.email);
                MsgBox.alert(this, "Lấy lại mật khẩu thành công!!!");
                new Login_Frame().setVisible(true);
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_lbl_DatLaiMatKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new doiMatKhau().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEye;
    private javax.swing.JLabel lblSlash;
    private javax.swing.JLabel lblSpantext;
    private javax.swing.JLabel lblSpantext1;
    private javax.swing.JLabel lbl_DatLaiMatKhau;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
