/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonesystem.edu.view;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import phonesystem.edu.dao.NhanVienDAO;
import phonesystem.edu.dao.TaiKhoanDAO;
import phonesystem.edu.entity.NhanVien;
import phonesystem.edu.entity.TaiKhoan;
import phonesystem.edu.ultil.Auth;
import phonesystem.edu.ultil.MsgBox;
import phonesystem.edu.ultil.XImage;

/**
 *
 * @author HienTran
 */
public class Login_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Login_Frame
     */
//    Get userName Login
    static String userName;

//    Get userName login recent
    String LoginAcountRecent1;
    String LoginAcountRecent2;

    public Login_Frame() {
        initComponents();
        this.requestFocus();
        this.init();
    }

    private void init() {
        txt_TenDangNhap.setBackground(new Color(0, 0, 0, 1));
        txt_MatKhau.setBackground(new Color(0, 0, 0, 1));
        txt_MatKhau.setBackground(new Color(0, 0, 0, 1));

//        Password
        lblSlash.setVisible(false);

        //        UserName recent
        if (Main_Frame.checkBox1 == true) {
            LoginAcountRecent1 = Main_Frame.LoginAccount1;
            txt_TenDangNhap.setText(LoginAcountRecent1);
            return;
        }

        if (Main_Frame.checkBox2 == true) {
            LoginAcountRecent2 = Main_Frame.LoginAccount2;
            txt_TenDangNhap.setText(LoginAcountRecent2);
        }

//        Icon image , Title FRAME
        setIconImage(XImage.getAppIcon());
        this.setTitle("Đăng nhập");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblEye = new javax.swing.JLabel();
        lblSlash = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_TenDangNhap = new javax.swing.JTextField();
        txt_MatKhau = new javax.swing.JPasswordField();
        lbl_quenmatkhau = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/login_img.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/icons8_eye_23px.png"))); // NOI18N
        lblEye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEyeMouseClicked(evt);
            }
        });
        jPanel3.add(lblEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 112, 30, 23));

        lblSlash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/icons8_blind_23px.png"))); // NOI18N
        lblSlash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSlash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSlashMouseClicked(evt);
            }
        });
        jPanel3.add(lblSlash, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 112, 30, 23));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel2.setText("Login");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setForeground(new java.awt.Color(113, 113, 113));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/icons8_user_23px.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 69, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/icons8_forgot_password_23px_1.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 114, 22, -1));

        txt_TenDangNhap.setForeground(new java.awt.Color(113, 113, 113));
        txt_TenDangNhap.setText("Tên đăng nhập");
        txt_TenDangNhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(131, 131, 131)));
        txt_TenDangNhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_TenDangNhapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TenDangNhapFocusLost(evt);
            }
        });
        txt_TenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenDangNhapActionPerformed(evt);
            }
        });
        jPanel3.add(txt_TenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 67, 232, 25));

        txt_MatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(131, 131, 131)));
        txt_MatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatKhauActionPerformed(evt);
            }
        });
        jPanel3.add(txt_MatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 111, 232, 25));

        lbl_quenmatkhau.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_quenmatkhau.setText("Quên mật khẩu?");
        lbl_quenmatkhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_quenmatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_quenmatkhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_quenmatkhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_quenmatkhauMouseExited(evt);
            }
        });
        jPanel3.add(lbl_quenmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jPanel1.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/login.png"))); // NOI18N
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        jPanel2.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 29));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(113, 113, 113));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("OR");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 59, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 67, 114, 10));

        jSeparator2.setMaximumSize(new java.awt.Dimension(120, 1));
        jSeparator2.setMinimumSize(new java.awt.Dimension(120, 1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 65, 120, 12));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phonesystem/edu/img/Group 19.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 30));

        jPanel1.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEyeMouseClicked
        lblSlash.setVisible(true);
        lblEye.setVisible(false);
        txt_MatKhau.setEchoChar((char) 0);
    }//GEN-LAST:event_lblEyeMouseClicked

    private void lblSlashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSlashMouseClicked
        lblSlash.setVisible(false);
        lblEye.setVisible(true);
        txt_MatKhau.setEchoChar('.');
    }//GEN-LAST:event_lblSlashMouseClicked

    private void txt_TenDangNhapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TenDangNhapFocusGained
        if (txt_TenDangNhap.getText().equals("Tên đăng nhập")) {
            txt_TenDangNhap.setText("");
        }
    }//GEN-LAST:event_txt_TenDangNhapFocusGained

    private void txt_TenDangNhapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TenDangNhapFocusLost
        if (txt_TenDangNhap.getText().length() == 0) {
            txt_TenDangNhap.setText("Tên đăng nhập");
        }
    }//GEN-LAST:event_txt_TenDangNhapFocusLost

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        this.Login();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void txt_TenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenDangNhapActionPerformed
        this.Login();
    }//GEN-LAST:event_txt_TenDangNhapActionPerformed

    private void txt_MatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatKhauActionPerformed
        this.Login();
    }//GEN-LAST:event_txt_MatKhauActionPerformed

    private void lbl_quenmatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_quenmatkhauMouseClicked
        new nhapEmail().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_quenmatkhauMouseClicked

    private void lbl_quenmatkhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_quenmatkhauMouseEntered
        lbl_quenmatkhau.setForeground(new Color(15,63,208));
    }//GEN-LAST:event_lbl_quenmatkhauMouseEntered

    private void lbl_quenmatkhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_quenmatkhauMouseExited
        lbl_quenmatkhau.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lbl_quenmatkhauMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login_Frame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEye;
    public javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSlash;
    private javax.swing.JLabel lbl_quenmatkhau;
    public javax.swing.JPasswordField txt_MatKhau;
    public javax.swing.JTextField txt_TenDangNhap;
    // End of variables declaration//GEN-END:variables

    TaiKhoanDAO dao = new TaiKhoanDAO();
    TaiKhoan tk = new TaiKhoan();

    public boolean check() {
        if (txt_TenDangNhap.getText().equals("")) {
            txt_TenDangNhap.requestFocus();
            MsgBox.alert(this, "Chưa nhập vào tên đăng nhập");
            return false;
        } else if (txt_MatKhau.getPassword().length == 0) {
            MsgBox.alert(this, "Chưa nhập vào mật khẩu");
            txt_MatKhau.requestFocus();
            return false;
        }

        return true;
    }
    NhanVienDAO nvDAO = new NhanVienDAO();

    public void Login() {

        String tenDN = txt_TenDangNhap.getText();
        String Pass = String.valueOf(txt_MatKhau.getPassword());

        TaiKhoan tk = dao.selectByTenDangNhap(tenDN);

        if (check()) {
            if (tk == null) {
                MsgBox.alert(this, "Sai tên đăng nhập");
                txt_TenDangNhap.requestFocus();
            } else if (!Pass.equals(tk.getMatKhau())) {
                MsgBox.alert(this, "Mật khẩu không chính xác");
                txt_MatKhau.requestFocus();
            } else {
                Auth.user = tk;
                new Main_Frame().setVisible(true);
                NhanVien nv = nvDAO.selectByid(tk.getMaNhanVien());
                Main_Frame.lbl_TenNhanVien.setText(nv.getTenNhanVien());
                Auth.nv = nv;
                this.dispose();
            }
        }

    }
}
