/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonesystem.edu.view;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import phonesystem.edu.ultil.MsgBox;

/**
 *
 * @author NP
 */
public class Them_XuatXu extends javax.swing.JDialog {

    public static String XuatXu;

    /**
     * Creates new form Add_Hang
     */
    public Them_XuatXu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_ThemXuatXu = new javax.swing.JTextField();
        btn_ThemXuatXu = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông báo");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Nhập Xuất xứ");

        txt_ThemXuatXu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ThemXuatXuActionPerformed(evt);
            }
        });

        btn_ThemXuatXu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ThemXuatXu.setForeground(new java.awt.Color(0, 0, 204));
        btn_ThemXuatXu.setText("Thêm");
        btn_ThemXuatXu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemXuatXuActionPerformed(evt);
            }
        });

        btn_Huy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Huy.setForeground(new java.awt.Color(0, 0, 204));
        btn_Huy.setText("Hủy");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txt_ThemXuatXu)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_ThemXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56)
                            .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_ThemXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemXuatXuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemXuatXuActionPerformed
        if (kiemtraXuatXu()) {
            XuatXu = txt_ThemXuatXu.getText();
            int i = Main_Frame.cbo_XuatXu_SanPham.getItemCount();
            Main_Frame.cbo_XuatXu_SanPham.insertItemAt(XuatXu, i - 1);
            Main_Frame.cbo_XuatXu_SanPham.setSelectedIndex(i - 1);
            this.dispose();
        }
    }//GEN-LAST:event_btn_ThemXuatXuActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void txt_ThemXuatXuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ThemXuatXuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ThemXuatXuActionPerformed

    public boolean kiemtraXuatXu() {
        String strPattern = "[~!@#$%^&*()_+{}\\[\\]:;<>/?]";
        Pattern p = Pattern.compile(strPattern);
        Matcher matcherXuatXu = p.matcher(txt_ThemXuatXu.getText());

        if (txt_ThemXuatXu.getText().equals("")) {
            MsgBox.alert(this, "Vui lòng nhập vào Xuát xứ");
            txt_ThemXuatXu.requestFocus();
            return false;
        } else if (matcherXuatXu.find()) {
            MsgBox.alert(this, "Xuất xứ không được chứa kí tự đặc biệt");
            txt_ThemXuatXu.requestFocus();
            return false;
        }
        try {
            if (Integer.parseInt(txt_ThemXuatXu.getText()) > 0 || Integer.parseInt(txt_ThemXuatXu.getText()) < 0) {
                MsgBox.alert(this, "Xuất xứ phải là chữ !!!");
                txt_ThemXuatXu.requestFocus();
                return false;
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Xuất xứ phải là chữ !!!");
            txt_ThemXuatXu.requestFocus();
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Them_XuatXu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Them_XuatXu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Them_XuatXu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Them_XuatXu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Them_XuatXu dialog = new Them_XuatXu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_ThemXuatXu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_ThemXuatXu;
    // End of variables declaration//GEN-END:variables
}
